// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "config_decoder.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<8> config_decoder::ap_const_lv8_0 = "00000000";
const sc_lv<32> config_decoder::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic config_decoder::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic config_decoder::ap_const_logic_0 = sc_dt::Log_0;

config_decoder::config_decoder(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_proc13_U0 = new Block_proc13("Block_proc13_U0");
    Block_proc13_U0->ap_clk(ap_clk);
    Block_proc13_U0->ap_rst(ap_rst_n_inv);
    Block_proc13_U0->ap_start(Block_proc13_U0_ap_start);
    Block_proc13_U0->ap_done(Block_proc13_U0_ap_done);
    Block_proc13_U0->ap_continue(Block_proc13_U0_ap_continue);
    Block_proc13_U0->ap_idle(Block_proc13_U0_ap_idle);
    Block_proc13_U0->ap_ready(Block_proc13_U0_ap_ready);
    Block_proc13_U0->ctrl_V_V_TDATA(Block_proc13_U0_ctrl_V_V_TDATA);
    Block_proc13_U0->ctrl_V_V_TVALID(Block_proc13_U0_ctrl_V_V_TVALID);
    Block_proc13_U0->ctrl_V_V_TREADY(ctrl_V_V_TREADY);
    Block_proc13_U0->din_words_V_V_TDATA(Block_proc13_U0_din_words_V_V_TDATA);
    Block_proc13_U0->din_words_V_V_TVALID(Block_proc13_U0_din_words_V_V_TVALID);
    Block_proc13_U0->din_words_V_V_TREADY(din_words_V_V_TREADY);
    Block_proc13_U0->dout_words_V_V_TDATA(Block_proc13_U0_dout_words_V_V_TDATA);
    Block_proc13_U0->dout_words_V_V_TVALID(Block_proc13_U0_dout_words_V_V_TVALID);
    Block_proc13_U0->dout_words_V_V_TREADY(dout_words_V_V_TREADY);

    SC_METHOD(thread_Block_proc13_U0_ap_continue);

    SC_METHOD(thread_Block_proc13_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_Block_proc13_U0_start_full_n);

    SC_METHOD(thread_Block_proc13_U0_start_write);

    SC_METHOD(thread_ap_done);
    sensitive << ( Block_proc13_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_proc13_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( Block_proc13_U0_ap_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Block_proc13_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( Block_proc13_U0_ap_ready );

    SC_METHOD(thread_ctrl_V_V_TDATA);
    sensitive << ( Block_proc13_U0_ctrl_V_V_TDATA );

    SC_METHOD(thread_ctrl_V_V_TVALID);
    sensitive << ( Block_proc13_U0_ctrl_V_V_TVALID );

    SC_METHOD(thread_din_words_V_V_TDATA);
    sensitive << ( Block_proc13_U0_din_words_V_V_TDATA );

    SC_METHOD(thread_din_words_V_V_TVALID);
    sensitive << ( Block_proc13_U0_din_words_V_V_TVALID );

    SC_METHOD(thread_dout_words_V_V_TDATA);
    sensitive << ( Block_proc13_U0_dout_words_V_V_TDATA );

    SC_METHOD(thread_dout_words_V_V_TVALID);
    sensitive << ( Block_proc13_U0_dout_words_V_V_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "config_decoder_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, din_words_V_V_TDATA, "(port)din_words_V_V_TDATA");
    sc_trace(mVcdFile, dout_words_V_V_TDATA, "(port)dout_words_V_V_TDATA");
    sc_trace(mVcdFile, ctrl_V_V_TDATA, "(port)ctrl_V_V_TDATA");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ctrl_V_V_TVALID, "(port)ctrl_V_V_TVALID");
    sc_trace(mVcdFile, ctrl_V_V_TREADY, "(port)ctrl_V_V_TREADY");
    sc_trace(mVcdFile, din_words_V_V_TVALID, "(port)din_words_V_V_TVALID");
    sc_trace(mVcdFile, din_words_V_V_TREADY, "(port)din_words_V_V_TREADY");
    sc_trace(mVcdFile, dout_words_V_V_TVALID, "(port)dout_words_V_V_TVALID");
    sc_trace(mVcdFile, dout_words_V_V_TREADY, "(port)dout_words_V_V_TREADY");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_proc13_U0_ap_start, "Block_proc13_U0_ap_start");
    sc_trace(mVcdFile, Block_proc13_U0_ap_done, "Block_proc13_U0_ap_done");
    sc_trace(mVcdFile, Block_proc13_U0_ap_continue, "Block_proc13_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc13_U0_ap_idle, "Block_proc13_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc13_U0_ap_ready, "Block_proc13_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc13_U0_ctrl_V_V_TDATA, "Block_proc13_U0_ctrl_V_V_TDATA");
    sc_trace(mVcdFile, Block_proc13_U0_ctrl_V_V_TVALID, "Block_proc13_U0_ctrl_V_V_TVALID");
    sc_trace(mVcdFile, Block_proc13_U0_din_words_V_V_TDATA, "Block_proc13_U0_din_words_V_V_TDATA");
    sc_trace(mVcdFile, Block_proc13_U0_din_words_V_V_TVALID, "Block_proc13_U0_din_words_V_V_TVALID");
    sc_trace(mVcdFile, Block_proc13_U0_dout_words_V_V_TDATA, "Block_proc13_U0_dout_words_V_V_TDATA");
    sc_trace(mVcdFile, Block_proc13_U0_dout_words_V_V_TVALID, "Block_proc13_U0_dout_words_V_V_TVALID");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, Block_proc13_U0_start_full_n, "Block_proc13_U0_start_full_n");
    sc_trace(mVcdFile, Block_proc13_U0_start_write, "Block_proc13_U0_start_write");
#endif

    }
    mHdltvinHandle.open("config_decoder.hdltvin.dat");
    mHdltvoutHandle.open("config_decoder.hdltvout.dat");
}

config_decoder::~config_decoder() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_proc13_U0;
}

void config_decoder::thread_Block_proc13_U0_ap_continue() {
    Block_proc13_U0_ap_continue = ap_const_logic_1;
}

void config_decoder::thread_Block_proc13_U0_ap_start() {
    Block_proc13_U0_ap_start = ap_start.read();
}

void config_decoder::thread_Block_proc13_U0_start_full_n() {
    Block_proc13_U0_start_full_n = ap_const_logic_1;
}

void config_decoder::thread_Block_proc13_U0_start_write() {
    Block_proc13_U0_start_write = ap_const_logic_0;
}

void config_decoder::thread_ap_done() {
    ap_done = Block_proc13_U0_ap_done.read();
}

void config_decoder::thread_ap_idle() {
    ap_idle = Block_proc13_U0_ap_idle.read();
}

void config_decoder::thread_ap_ready() {
    ap_ready = Block_proc13_U0_ap_ready.read();
}

void config_decoder::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void config_decoder::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void config_decoder::thread_ap_sync_done() {
    ap_sync_done = Block_proc13_U0_ap_done.read();
}

void config_decoder::thread_ap_sync_ready() {
    ap_sync_ready = Block_proc13_U0_ap_ready.read();
}

void config_decoder::thread_ctrl_V_V_TDATA() {
    ctrl_V_V_TDATA = Block_proc13_U0_ctrl_V_V_TDATA.read();
}

void config_decoder::thread_ctrl_V_V_TVALID() {
    ctrl_V_V_TVALID = Block_proc13_U0_ctrl_V_V_TVALID.read();
}

void config_decoder::thread_din_words_V_V_TDATA() {
    din_words_V_V_TDATA = Block_proc13_U0_din_words_V_V_TDATA.read();
}

void config_decoder::thread_din_words_V_V_TVALID() {
    din_words_V_V_TVALID = Block_proc13_U0_din_words_V_V_TVALID.read();
}

void config_decoder::thread_dout_words_V_V_TDATA() {
    dout_words_V_V_TDATA = Block_proc13_U0_dout_words_V_V_TDATA.read();
}

void config_decoder::thread_dout_words_V_V_TVALID() {
    dout_words_V_V_TVALID = Block_proc13_U0_dout_words_V_V_TVALID.read();
}

void config_decoder::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvoutHandle << mComma << "{"  <<  " \"din_words_V_V_TDATA\" :  \"" << din_words_V_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_words_V_V_TDATA\" :  \"" << dout_words_V_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ctrl_V_V_TDATA\" :  \"" << ctrl_V_V_TDATA.read() << "\" ";
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ctrl_V_V_TVALID\" :  \"" << ctrl_V_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ctrl_V_V_TREADY\" :  \"" << ctrl_V_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_words_V_V_TVALID\" :  \"" << din_words_V_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_words_V_V_TREADY\" :  \"" << din_words_V_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_words_V_V_TVALID\" :  \"" << dout_words_V_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dout_words_V_V_TREADY\" :  \"" << dout_words_V_V_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

