-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Block_proc13 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ctrl_V_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    ctrl_V_V_TVALID : OUT STD_LOGIC;
    ctrl_V_V_TREADY : IN STD_LOGIC;
    din_words_V_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    din_words_V_V_TVALID : OUT STD_LOGIC;
    din_words_V_V_TREADY : IN STD_LOGIC;
    dout_words_V_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    dout_words_V_V_TVALID : OUT STD_LOGIC;
    dout_words_V_V_TREADY : IN STD_LOGIC );
end;


architecture behav of Block_proc13 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ctrl_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal din_words_V_V_TDATA_blk_n : STD_LOGIC;
    signal dout_words_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal p_Result_s_fu_71_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_1_fu_83_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal regslice_both_ctrl_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_din_words_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_words_V_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ctrl_V_V_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal ctrl_V_V_TVALID_int : STD_LOGIC;
    signal ctrl_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_ctrl_V_V_U_vld_out : STD_LOGIC;
    signal din_words_V_V_TVALID_int : STD_LOGIC;
    signal din_words_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_din_words_V_V_U_vld_out : STD_LOGIC;
    signal dout_words_V_V_TVALID_int : STD_LOGIC;
    signal dout_words_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_dout_words_V_V_U_vld_out : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_ctrl_V_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ctrl_V_V_TDATA_int,
        vld_in => ctrl_V_V_TVALID_int,
        ack_in => ctrl_V_V_TREADY_int,
        data_out => ctrl_V_V_TDATA,
        vld_out => regslice_both_ctrl_V_V_U_vld_out,
        ack_out => ctrl_V_V_TREADY,
        apdone_blk => regslice_both_ctrl_V_V_U_apdone_blk);

    regslice_both_din_words_V_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv8_10,
        vld_in => din_words_V_V_TVALID_int,
        ack_in => din_words_V_V_TREADY_int,
        data_out => din_words_V_V_TDATA,
        vld_out => regslice_both_din_words_V_V_U_vld_out,
        ack_out => din_words_V_V_TREADY,
        apdone_blk => regslice_both_din_words_V_V_U_apdone_blk);

    regslice_both_dout_words_V_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv8_10,
        vld_in => dout_words_V_V_TVALID_int,
        ack_in => dout_words_V_V_TREADY_int,
        data_out => dout_words_V_V_TDATA,
        vld_out => regslice_both_dout_words_V_V_U_vld_out,
        ack_out => dout_words_V_V_TREADY,
        apdone_blk => regslice_both_dout_words_V_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((regslice_both_dout_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_din_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_ctrl_V_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_io, regslice_both_ctrl_V_V_U_apdone_blk, regslice_both_din_words_V_V_U_apdone_blk, regslice_both_dout_words_V_V_U_apdone_blk, ap_block_state2_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((regslice_both_dout_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_din_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_ctrl_V_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_io_assign_proc : process(ctrl_V_V_TREADY_int, din_words_V_V_TREADY_int, dout_words_V_V_TREADY_int)
    begin
                ap_block_state1_io <= ((dout_words_V_V_TREADY_int = ap_const_logic_0) or (din_words_V_V_TREADY_int = ap_const_logic_0) or (ctrl_V_V_TREADY_int = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(regslice_both_ctrl_V_V_U_apdone_blk, regslice_both_din_words_V_V_U_apdone_blk, regslice_both_dout_words_V_V_U_apdone_blk)
    begin
                ap_block_state2 <= ((regslice_both_dout_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_din_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_ctrl_V_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state2_io_assign_proc : process(ctrl_V_V_TREADY_int, din_words_V_V_TREADY_int, dout_words_V_V_TREADY_int)
    begin
                ap_block_state2_io <= ((dout_words_V_V_TREADY_int = ap_const_logic_0) or (din_words_V_V_TREADY_int = ap_const_logic_0) or (ctrl_V_V_TREADY_int = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, regslice_both_ctrl_V_V_U_apdone_blk, regslice_both_din_words_V_V_U_apdone_blk, regslice_both_dout_words_V_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((regslice_both_dout_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_din_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_ctrl_V_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_ctrl_V_V_U_apdone_blk, regslice_both_din_words_V_V_U_apdone_blk, regslice_both_dout_words_V_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((regslice_both_dout_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_din_words_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_ctrl_V_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ctrl_V_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_CS_fsm_state2, ctrl_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ctrl_V_V_TDATA_blk_n <= ctrl_V_V_TREADY_int;
        else 
            ctrl_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ctrl_V_V_TDATA_int <= (p_Result_1_fu_83_p5(31 downto 7) & ap_const_lv7_0);
    ctrl_V_V_TVALID <= regslice_both_ctrl_V_V_U_vld_out;

    ctrl_V_V_TVALID_int_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ctrl_V_V_TVALID_int <= ap_const_logic_1;
        else 
            ctrl_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    din_words_V_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_CS_fsm_state2, din_words_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            din_words_V_V_TDATA_blk_n <= din_words_V_V_TREADY_int;
        else 
            din_words_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    din_words_V_V_TVALID <= regslice_both_din_words_V_V_U_vld_out;

    din_words_V_V_TVALID_int_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            din_words_V_V_TVALID_int <= ap_const_logic_1;
        else 
            din_words_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    dout_words_V_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_CS_fsm_state2, dout_words_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dout_words_V_V_TDATA_blk_n <= dout_words_V_V_TREADY_int;
        else 
            dout_words_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_words_V_V_TVALID <= regslice_both_dout_words_V_V_U_vld_out;

    dout_words_V_V_TVALID_int_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_io)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state1_io) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dout_words_V_V_TVALID_int <= ap_const_logic_1;
        else 
            dout_words_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_83_p5 <= (p_Result_s_fu_71_p5(31 downto 24) & ap_const_lv16_0 & p_Result_s_fu_71_p5(7 downto 0));
    p_Result_s_fu_71_p5 <= (ap_const_lv8_0 & ap_const_lv32_0(23 downto 0));
end behav;
